#!/usr/bin/env bash
nc=${RNC_NC:-nc}
timeout=${RNC_TIMEOUT:-1}
tries=0

while true; do
  "$nc" $@
  sleep $timeout
  ((tries++))
  if [[ -n $RNC_MAX_TRIES && $tries -ge $RNC_MAX_TRIES ]]; then
    exit 1
  fi
done
